# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7af06f7c777ff1d08cd9318b23236e42352f95ce7081bfc516d161fd96b807162de2e8f2f9ac24fe3e187c3bb7e063b45293a30ace0edf4d987bee67a77b9b8

test:
  secret_key_base: 4dad6ee648811b5963ddf931d5aaf22cc0a11022852a3ba77d8771d6c4fc66085257300c3ecbf20d6827c06e0d135bdeb2aa9761abea49bf1827811323a20250

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
